### ISSUE TITLE
test outputs 

### ISSUE THREAD

**Issue by aharmax** [vadim0x60/heartpole#1]
Hi, many thanks for the great package. This must be simple but I would like to dump all outputs of
sarsa.test(heartpole, nb_episodes=1,
           nb_max_episode_steps=1000,
           visualize=True)
to a file that I can analyze/visualizer later. What would be the best way to do this?

**Comment by vadim0x60** [comment]
Try

```
history = sarsa.test(heartpole, nb_episodes=1, nb_max_episode_steps=1000, visualize=True)
with open('path/to/file', 'wb') as f:
  pickle.dump(history.history, f)
```

**Comment by aharmax** [comment]
This only gives the last result: 

{'episode_reward': [-299.9525253567738], 'nb_steps': [1000]}

It seems I have to add a new method to TestLogger callback because it only has that at the end, 

.. or just pipe it to a file with >, which is what I am doing now. Tx!

**Comment by vadim0x60** [comment]
OK, seems like we have a solution
Feel free to reopen if you think we should make this operation easier
